xcopy \\10.63.1.11\FOSSEP\NVOS-APLICATIVOS\FORM\*.fMX /s c:\FOSSEP\NVOS-APLICATIVOS\FORM\*.* /y
xcopy \\10.63.1.11\FOSSEP\NVOS-APLICATIVOS\FORM\*.MMX /s c:\FOSSEP\NVOS-APLICATIVOS\FORM\*.* /y
xcopy \\10.63.1.11\FOSSEP\NVOS-APLICATIVOS\REPORT\*.rep /s c:\FOSSEP\NVOS-APLICATIVOS\REPORT\*.* /y






